### PR TITLE
Fixed typo errors

### PR DESCRIPTION
**Pull request by Ananthavijay**
fixes this [issue](https://github.com/yogdaan/git-from-scratch/issues/3) .

### CODE REVIEW

**Comment by gabru-md** [comment]
Can we just rework the whole readme, at first It was a project that I started so I made the readme like this.
We can modify the readme to make it look apt for the contributors as well.
@Ananthavijay Can you make these changes,please ?

**Comment by Ananthavijay** [comment]
Yes sure. tell me @gabru-md

**Comment by gabru-md** [comment]
Let me merge this first. 
I'll open a new issue for you to claim where we will let you know what to update in readme. 
Meanwhile you can join us on our [gitter channel](https://gitter.im/yogdaan/lobby)

**Comment by Ananthavijay** [comment]
Yes. thanks

**Pull request merged**
